- hosts: all
  remote_user: cephadmin
  become: yes
  become_user: root
  become_method: sudo
  tasks:
#  - name: add_key
#    command: "wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -"
  - name: add cph repo
    copy:
      src: /etc/apt/sources.list.d/ceph.list
      dest: /etc/apt/sources.list.d/ceph.list
  - name: copy hosts file
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  - name: copy sysctl
    copy:
      src: /etc/sysctl.conf
      dest: /etc/sysctl.conf
  - name: grub_disable_ipv6
    copy:
      src: /etc/default/grub
      dest: /etc/default/grub
    register: grub
  - name: grub update
    command: /usr/sbin/update-grub update
    when: grub.changed
  - name: install pkgs
    apt:
      name: "{{ item }}"
    with_items:
      - ntp
      - bash-completion
      - python-minimal
